### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by dherkova** [asutera/kaggle-connectomics#1]
Hi,
I tried running the code in a fresh anaconda environment but ran into some issues. What version of scikit-learn did you use exactly?
Althought you state that `scikit-learn >= 0.14` , running the code with 0.14.1 fails at the call `pca.get_precision()`. It apepars that this function is only present in the current master branch of scikit-learn and not in 0.14. Did you compile scikit-learn from the current repository?

**Comment by arjoly** [comment]
Thanks for pointing the issue. Apparently, we were working with the master branch.
The last time that we updated the clone, the master branch was at the commit `8d04380d474723467b5a717328efd0c9fc5bd898`. 

To get the it works, you can do

```
git clone git@github.com:scikit-learn/scikit-learn.git
pip install -e scikit-learn
```

 or 

```
git clone git@github.com:scikit-learn/scikit-learn.git
cd scikit-learn
git checkout 8d04380d474723467b5a717328efd0c9fc5bd898
pip install -e .
```

Sorry for the inconvenience, I will update the readme.
