### ISSUE TITLE
'PCA' attribute has no attribute 'get_precision'

### ISSUE THREAD

**Issue by vivekveeriah** [asutera/kaggle-connectomics#3]
I was trying to run your code on normal-1 dataset, and got this error

$ python main.py -f ../normal-1/fluorescence_normal-1.txt -o AAAGVrun1.csv -n normal-1
Loading data...
Making simple inference...
Current: 0.100, f1
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    y_pca = make_simple_inference(X)
  File "/home/vivek/KDD/AAAGV/PCA.py", line 120, in make_simple_inference
    y_pred = - pca.get_precision()
AttributeError: 'PCA' object has no attribute 'get_precision'

**Comment by arjoly** [comment]
What is your version of scikit-learn?
Did you try with the latest released version?

**Comment by vivekveeriah** [comment]
The version is 0.14.1

**Comment by arjoly** [comment]
If you upgrade to 0.15, it should work.

**Comment by vivekveeriah** [comment]
Thanks !!
The upgrade works !!

**Comment by arjoly** [comment]
Good, then I am closing.
